Assets/Scripts/Wallet/Settings.cs

Fix for https://phantasma.atlassian.net/browse/POL-22
"Unknown" nexus was selected on fresh install.

Use mainnet on fresh install

---

Assets/Scripts/Wallet/Settings.cs

fix incorrect default bp url

---

Assets/Scripts/Wallet/AccountManager.cs

Fix for https://phantasma.atlassian.net/browse/POL-21

Fix NEO addresses missing from send address combo

---

Assets/Scripts/Wallet/WalletGUI.cs

Fix for https://phantasma.atlassian.net/browse/POL-29

Fix displayed NEO destination address when swapping

---

Assets/Scripts/Wallet/WalletGUI.cs

Modification for https://phantasma.atlassian.net/browse/POL-7

Add a copy to clipboard for the seed words

---

Assets/Scripts/Wallet/WalletGUI.cs

Fix for https://phantasma.atlassian.net/browse/POL-35

Fix wallet name length limits inconsistency

---

Assets/Scripts/Wallet/WalletGUI.cs

Fix for https://phantasma.atlassian.net/browse/POL-31

Fix inconsistent behavior after wallet creation error

---

.gitignore
Assets/Scripts/Wallet/Log.cs
Assets/Scripts/Wallet/Log.cs.meta
Assets/Scripts/Wallet/Settings.cs
Assets/Scripts/Wallet/WalletGUI.cs
Assets/Scripts/Wallet/WebClient.cs

Would be great to have logging in Poltergeist to help with it's support and bug fixing.

Add logging

---

Assets/Scripts/Wallet/WalletGUI.cs

Fix for https://phantasma.atlassian.net/browse/POL-32

Fix uneven buttons spacing in dialogs and button grids

---

Assets/Scripts/Wallet/WalletGUI.cs

Modification for https://phantasma.atlassian.net/browse/POL-34

Add "Cancel" button to settings window

---

Assets/Scripts/Wallet/WalletGUI.cs

Needed to properly show all fields in "Custom" mode.
Fix for https://phantasma.atlassian.net/browse/POL-33

Add vertical scroll in settings

---

Assets/Scripts/Wallet/WebClient.cs

Will help to find the reason of this problem: https://phantasma.atlassian.net/browse/POL-20

Better error description for WEB_REQUEST_ERROR

---

Assets/Scripts/Wallet/WalletGUI.cs

Fix for https://phantasma.atlassian.net/browse/POL-41

Fix for "Cancel" button in "Delete Everything" prompt

---

Assets/Scripts/Wallet/WalletGUI.cs

1) Fix for 2 buttons in vertical layout
2) Fix for 1 button in both layouts

Additional fixes for uneven button spacings in modal dialogs

---

Assets/Scripts/Wallet/WalletGUI.cs

Fix for https://phantasma.atlassian.net/browse/POL-40

Fix overlapping labels when pending SOUL is available

---

Assets/Neo/Core/NeoAPI.cs
Assets/Scripts/Wallet/AccountManager.cs
Assets/Scripts/Wallet/CoroutineUtils.cs
Assets/Scripts/Wallet/CoroutineUtils.cs.meta

As noted by Vincent here: https://phantasma.atlassian.net/browse/POL-20
We should not crash whole wallet if neo rpc is not responding.

Make Neo transfer error non-fatal

---

ProjectSettings/GraphicsSettings.asset
ProjectSettings/ProjectVersion.txt
ProjectSettings/UnityConnectSettings.asset

To temporary solve this issue with scrolling: https://phantasma.atlassian.net/browse/POL-28

Downgrade Unity project to 2019.2.11

---

Assets/Scripts/Wallet/ComboBox.cs
Assets/Scripts/Wallet/WalletGUI.cs

Fix for https://phantasma.atlassian.net/browse/POL-11

Add scroll to address hint combo

---

Assets/Scripts/Wallet/ConnectorManager.cs

Needed to help with investigation of https://phantasma.atlassian.net/browse/POL-36

ConnectorManager logging

---

Assets/Scripts/Wallet/AccountManager.cs

And for goati token - divisible.
Fix for https://phantasma.atlassian.net/browse/POL-43

Make non-nft phantasma tokens transferable

---

Assets/Scripts/Wallet/AccountManager.cs

Aslo fixes this: https://phantasma.atlassian.net/browse/POL-44

Fix link connection to a closed account

---

Assets/Scripts/Wallet/AccountManager.cs

update rpc peers URL

---

Assets/Scripts/Wallet/DescriptionUtils.cs

Partial improvement for this ticket: https://phantasma.atlassian.net/browse/POL-62
Also fixes src and dst address parsing for "Runtime.TransferTokens".

Better description for market.BuyToken

---

Assets/Scripts/Wallet/WalletGUI.cs

Modification for this ticket: https://phantasma.atlassian.net/browse/POL-49

Add copy to clipboard button for error dialogs

---

Assets/Scripts/Wallet/WalletGUI.cs

Add Cancel button to transaction preparation dialog

---

Assets/Scripts/Wallet/WalletGUI.cs

Fix for: https://phantasma.atlassian.net/browse/POL-50

Center history view button

---

Assets/Scripts/Wallet/AccountManager.cs
Assets/Scripts/Wallet/Tokens.cs

Fix the deadlock

---

Assets/Plugins/NBitcoin/Newtonsoft.Json.dll.meta
Assets/Scripts/Wallet/Settings.cs

- Change testnet explorer link

Development 

---

Assets/Phantasma/Phantasma.Core/src/Domain/WalletLink.cs
Assets/Scripts/Wallet/AccountManager.cs
Assets/Scripts/Wallet/AccountManagerClasses/AccountState.cs
Assets/Scripts/Wallet/Settings.cs
Assets/Scripts/Wallet/WalletGUIFolder/WalletGUI.cs
Assets/Scripts/Wallet/WalletLink/WalletConnector.cs
ProjectSettings/ProjectSettings.asset

- Added Get Wallet Version
- Fixed GetPeer and GetNexus
- Fixed Neo Address but not data
- Fixed some issues related to balances

Improvements and Bug fix's
